# schema.yml
#Dataset: gz_raw_data
#Tables:
#raw_gz_sales
#raw_gz_product
#raw_gz_ship

version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
       - name: sales
         identifier: raw_gz_sales
         description: informations about product sales (dates, orders id, revenue, quantity)
         loaded_at_field: CAST(date_date AS TIMESTAMP)
         freshness: 
           warn_after:
             count: 90
             period: day
         
         columns:
           - name: date_date
             description: date of purchase
             
           - name: orders_id
             description: orders id 

           - name: products_id	
             description: product id 
          
           - name: revenue
             description: revenue from purchase
           - name: quantity
             description: quantity of items in purchase
          
       - name: product
         identifier: raw_gz_product
         description: informations about products id and price
         columns:
           - name: products_id
             description: products id -- primary key
             tests:
               - unique
               - not_null
           - name: purchase_price
             description: purchase price
       - name: ship
         identifier: raw_gz_ship
         description: informations about products delivery (shipping fee and cost)
         columns:
           - name: orders_id
             description: orders id
             tests:
               - unique
               - not_null
           - name: shipping_fee
             description: shipping fee
           - name: logcost
             description: logistic costs
           - name: ship_cost
             description: shipping cost

             